### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jessherna** [jessherna/comp-123_group3_winter2023_banking-app#5]

**Comment by jessherna** [comment]
Pushed Test Harness to the master branch under the Bank class.

The test harness code intentionally triggers exception and it stops the code from running. 
Commented out the Withdrawal attempts prior to approaching Overdraft for the CheckingAccount CK-100005
![Image](https://user-images.githubusercontent.com/126341255/229953144-7ee644dd-7661-4adc-807f-2fd556ae0cd5.png)
![Image](https://user-images.githubusercontent.com/126341255/229953338-d157abe5-2012-48f9-8b3d-8b661b1f7368.png)

**Comment by jessherna** [comment]
Re-do everything because the correct reference is the Assignment 04 - Accounts on Week 11

**Comment by StephCor123** [comment]
Let's try it again.

**Comment by jessherna** [comment]
> Re-do everything because the correct reference is the Assignment 04 - Accounts on Week 11

Created a new test harness. 
Remaining issue is the balance inconsistencies Before and After PrepareMonthlyReport().

Created a separate issue on Logger.

**Comment by jessherna** [comment]
> > Re-do everything because the correct reference is the Assignment 04 - Accounts on Week 11
> 
> Created a new test harness. Remaining issue is the balance inconsistencies Before and After PrepareMonthlyReport().
> 
> Created a separate issue on Logger.

Removed  / 12 in the interest calculation.
For VisaAccount used Balance += interest instead of Balance -= interest.
